FROM redis:6.2.6
WORKDIR /redis
COPY redis-sentinel.conf /redis/
COPY ./scripts/ /scripts/
ENV REDIS_SENTINEL_CONF /redis/redis-sentinel.conf
ENTRYPOINT [ "sh","-c","redis-sentinel", "${REDIS_SENTINEL_CONF}" ]